apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-otus
  template:
    metadata:
      labels:
        app: myapp-otus
    spec:
      containers:
        - name: otus-myapp
          image: 757grok/alag:otus-myapp
          ports:
            - name: web
              containerPort: 8000
