apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-otus
  template:
    metadata:
      labels:
        app: myapp-otus
    spec:
      containers:
        - name: otus-myapp
          image: 757grok/alag:otus-myapp
          imagePullPolicy: Always
          env:
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URI
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_PASSWORD
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
