apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATABASE_URI: {{.Values.postgresql.postgresqlUri}}
  DATABASE_NAME: {{.Values.postgresql.postgresqlDatabase}}
  DATABASE_USER: {{.Values.postgresql.postgresqlUsername}}
  DATABASE_PASSWORD: {{.Values.postgresql.postgresqlPassword}}