apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-app-chart
  labels:
    helm.sh/chart: app-chart-0.1.0
    app.kubernetes.io/name: app-chart
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: app-chart
      app.kubernetes.io/instance: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-chart
        app.kubernetes.io/instance: myapp
      annotations:
        checksum/config: f17b65735efe685aa6224782f16204b2ec8f9e7ac71aedf3a6e8044d9b29c456
    spec:
      containers:
        - name: app-chart
          image: "757grok/alag:otus-myapp"
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URI
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_NAME
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_PASSWORD
