apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  labels:
    helm.sh/chart: app-chart-0.1.0
    app.kubernetes.io/name: app-chart
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: myapp
  annotations:
    ubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /?(.*)
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: myapp-app-chart
                port:
                  number: 8000