apiVersion: v1
kind: Service
metadata:
   name:  myapp-app-chart
   labels:
     {{- include "app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "app-chart.selectorLabels" . | nindent 4 }}
