CREATE TABLE USERS {
    USER_ID SERIAL PRIMARY KEY,
    USER_NAME VARCHAR(30) NOT NULL,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    EMAIl_NAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
 }